 const province = [
    { value: 1, label: "An Giang" },
    { value: 2, label: "Bà Rịa – Vũng Tàu" },
    { value: 3, label: "Bắc Giang" },
    { value: 4, label: "Bắc Kạn" },
    { value: 5, label: "Bạc Liêu" },
    { value: 6, label: "Bắc Ninh" },
    { value: 7, label: "Bến Tre" },
    { value: 8, label: "Bình Định" },
    { value: 9, label: "Bình Dương" },
    { value: 10, label: "Bình Phước" },
    { value: 11, label: "Bình Thuận" },
    { value: 12, label: "Cà Mau" },
    { value: 13, label: "Cần Thơ" },
    { value: 14, label: "Cao Bằng" },
    { value: 15, label: "Đà Nẵng" },
    { value: 16, label: "Đắk Lắk" },
    { value: 17, label: "Đắk Nông" },
    { value: 18, label: "Điện Biên" },
    { value: 19, label: "Đồng Nai" },
    { value: 20, label: "Đồng Tháp" },
    { value: 21, label: "Gia Lai" },
    { value: 22, label: "Hà Giang" },
    { value: 23, label: "Hà Nam" },
    { value: 24, label: "Hà Nội" },
    { value: 25, label: "Hà Tĩnh" },
    { value: 26, label: "Hải Dương" },
    { value: 27, label: "Hải Phòng" },
    { value: 28, label: "Hậu Giang" },
    { value: 29, label: "Hòa Bình" },
    { value: 30, label: "Hưng Yên" },
    { value: 31, label: "Khánh Hòa" },
    { value: 32, label: "Kiên Giang" },
    { value: 33, label: "Kon Tum" },
    { value: 34, label: "Lai Châu" },
    { value: 35, label: "Lâm Đồng" },
    { value: 36, label: "Lạng Sơn" },
    { value: 37, label: "Lào Cai" },
    { value: 38, label: "Long An" },
    { value: 39, label: "Nam Định" },
    { value: 40, label: "Nghệ An" },
    { value: 41, label: "Ninh Bình" },
    { value: 42, label: "Ninh Thuận" },
    { value: 43, label: "Phú Thọ" },
    { value: 44, label: "Phú Yên" },
    { value: 45, label: "Quảng Bình" },
    { value: 46, label: "Quảng Nam" },
    { value: 47, label: "Quảng Ngãi" },
    { value: 48, label: "Quảng Ninh" },
    { value: 49, label: "Quảng Trị" },
    { value: 50, label: "Sóc Trăng" },
    { value: 51, label: "Sơn La" },
    { value: 52, label: "Tây Ninh" },
    { value: 53, label: "Thái Bình" },
    { value: 54, label: "Thái Nguyên" },
    { value: 55, label: "Thanh Hóa" },
    { value: 56, label: "Thừa Thiên Huế" },
    { value: 57, label: "Tiền Giang" },
    { value: 58, label: "TP Hồ Chí Minh" },
    { value: 59, label: "Trà Vinh" },
    { value: 60, label: "Tuyên Quang" },
    { value: 61, label: "Vĩnh Long" },
    { value: 62, label: "Vĩnh Phúc" },
    { value: 63, label: "Yên Bái" },
]

export default province